
// Package slot is generated by gogll. Do not edit. 
package slot

import(
	"bytes"
	"fmt"
	
	"github.com/goccmack/3nf/parser/symbols"
)

type Label int

const(
	AttributeDeclaration0R0 Label = iota
	AttributeDeclaration0R1
	AttributeDeclaration0R2
	AttributeDeclaration0R3
	AttributeDeclaration1R0
	AttributeDeclaration1R1
	AttributeDeclaration1R2
	AttributeDeclaration1R3
	AttributeDeclaration2R0
	AttributeDeclaration2R1
	AttributeDeclaration2R2
	AttributeDeclaration2R3
	AttributeDeclaration2R4
	AttributeDeclarations0R0
	AttributeDeclarations0R1
	AttributeDeclarations1R0
	AttributeDeclarations1R1
	AttributeDeclarations1R2
	AttributeName0R0
	AttributeName0R1
	Constraint0R0
	Constraint0R1
	Constraint1R0
	Constraint1R1
	Constraint2R0
	Constraint2R1
	Constraints0R0
	Constraints0R1
	Constraints0R2
	Constraints1R0
	Description0R0
	Description0R1
	Description1R0
	ERM0R0
	ERM0R1
	ERM0R2
	ERM1R0
	ERM1R1
	Entity0R0
	Entity0R1
	Entity0R2
	Entity0R3
	Entity0R4
	Entity1R0
	Entity1R1
	Entity1R2
	Entity1R3
	EntityName0R0
	EntityName0R1
	EntityOrEnum0R0
	EntityOrEnum0R1
	EntityOrEnum1R0
	EntityOrEnum1R1
	Enum0R0
	Enum0R1
	Enum0R2
	Enum0R3
	Enum0R4
	Enum0R5
	EnumItem0R0
	EnumItem0R1
	EnumItem0R2
	EnumItem0R3
	EnumItem0R4
	EnumItem0R5
	EnumItemName0R0
	EnumItemName0R1
	EnumItems0R0
	EnumItems0R1
	EnumItems0R2
	EnumItems1R0
	EnumItems1R1
	FieldName0R0
	FieldName0R1
	ForeignKey0R0
	ForeignKey0R1
	ForeignKey0R2
	ForeignKey0R3
	ForeignKey0R4
	Name0R0
	Name0R1
	Nullable0R0
	Nullable0R1
	Nullable1R0
	Nullable1R1
	Nullable1R2
	PrimaryKey0R0
	PrimaryKey0R1
	Schema0R0
	Schema0R1
	Schema0R2
	Schema0R3
	SchemaName0R0
	SchemaName0R1
	SequenceNumber0R0
	SequenceNumber0R1
	TypeName0R0
	TypeName0R1
	TypeName1R0
	TypeName1R1
	TypeName2R0
	TypeName2R1
	TypeName3R0
	TypeName3R1
	TypeName4R0
	TypeName4R1
	TypeName5R0
	TypeName5R1
	TypeName6R0
	TypeName6R1
	TypeName7R0
	TypeName7R1
	Unique0R0
	Unique0R1
)

type Slot struct {
	NT      symbols.NT
	Alt     int
	Pos     int
	Symbols symbols.Symbols
	Label 	Label
}

type Index struct {
	NT      symbols.NT
	Alt     int
	Pos     int
}

func GetAlternates(nt symbols.NT) []Label {
	alts, exist := alternates[nt]
	if !exist {
		panic(fmt.Sprintf("Invalid NT %s", nt))
	}
	return alts
}

func GetLabel(nt symbols.NT, alt, pos int) Label {
	l, exist := slotIndex[Index{nt,alt,pos}]
	if exist {
		return l
	}
	panic(fmt.Sprintf("Error: no slot label for NT=%s, alt=%d, pos=%d", nt, alt, pos))
}

func (l Label) EoR() bool {
	return l.Slot().EoR()
}

func (l Label) Head() symbols.NT {
	return l.Slot().NT
}

func (l Label) Index() Index {
	s := l.Slot()
	return Index{s.NT, s.Alt, s.Pos}
}

func (l Label) Alternate() int {
	return l.Slot().Alt
}

func (l Label) Pos() int {
	return l.Slot().Pos
}

func (l Label) Slot() *Slot {
	s, exist := slots[l]
	if !exist {
		panic(fmt.Sprintf("Invalid slot label %d", l))
	}
	return s
}

func (l Label) String() string {
	return l.Slot().String()
}

func (l Label) Symbols() symbols.Symbols {
	return l.Slot().Symbols
}

func (s *Slot) EoR() bool {
	return s.Pos >= len(s.Symbols)
}

func (s *Slot) String() string {
	buf := new(bytes.Buffer)
	fmt.Fprintf(buf, "%s : ", s.NT)
	for i, sym := range s.Symbols {
		if i == s.Pos {
			fmt.Fprintf(buf, "∙")
		}
		fmt.Fprintf(buf, "%s ", sym)
	}
	if s.Pos >= len(s.Symbols) {
		fmt.Fprintf(buf, "∙")
	}
	return buf.String()
}

var slots = map[Label]*Slot{ 
	AttributeDeclaration0R0: {
		symbols.NT_AttributeDeclaration, 0, 0, 
		symbols.Symbols{  
			symbols.NT_AttributeName, 
			symbols.NT_TypeName, 
			symbols.NT_PrimaryKey,
		}, 
		AttributeDeclaration0R0, 
	},
	AttributeDeclaration0R1: {
		symbols.NT_AttributeDeclaration, 0, 1, 
		symbols.Symbols{  
			symbols.NT_AttributeName, 
			symbols.NT_TypeName, 
			symbols.NT_PrimaryKey,
		}, 
		AttributeDeclaration0R1, 
	},
	AttributeDeclaration0R2: {
		symbols.NT_AttributeDeclaration, 0, 2, 
		symbols.Symbols{  
			symbols.NT_AttributeName, 
			symbols.NT_TypeName, 
			symbols.NT_PrimaryKey,
		}, 
		AttributeDeclaration0R2, 
	},
	AttributeDeclaration0R3: {
		symbols.NT_AttributeDeclaration, 0, 3, 
		symbols.Symbols{  
			symbols.NT_AttributeName, 
			symbols.NT_TypeName, 
			symbols.NT_PrimaryKey,
		}, 
		AttributeDeclaration0R3, 
	},
	AttributeDeclaration1R0: {
		symbols.NT_AttributeDeclaration, 1, 0, 
		symbols.Symbols{  
			symbols.NT_AttributeName, 
			symbols.NT_TypeName, 
			symbols.NT_Constraints,
		}, 
		AttributeDeclaration1R0, 
	},
	AttributeDeclaration1R1: {
		symbols.NT_AttributeDeclaration, 1, 1, 
		symbols.Symbols{  
			symbols.NT_AttributeName, 
			symbols.NT_TypeName, 
			symbols.NT_Constraints,
		}, 
		AttributeDeclaration1R1, 
	},
	AttributeDeclaration1R2: {
		symbols.NT_AttributeDeclaration, 1, 2, 
		symbols.Symbols{  
			symbols.NT_AttributeName, 
			symbols.NT_TypeName, 
			symbols.NT_Constraints,
		}, 
		AttributeDeclaration1R2, 
	},
	AttributeDeclaration1R3: {
		symbols.NT_AttributeDeclaration, 1, 3, 
		symbols.Symbols{  
			symbols.NT_AttributeName, 
			symbols.NT_TypeName, 
			symbols.NT_Constraints,
		}, 
		AttributeDeclaration1R3, 
	},
	AttributeDeclaration2R0: {
		symbols.NT_AttributeDeclaration, 2, 0, 
		symbols.Symbols{  
			symbols.NT_AttributeName, 
			symbols.NT_TypeName, 
			symbols.T_5, 
			symbols.NT_Constraints,
		}, 
		AttributeDeclaration2R0, 
	},
	AttributeDeclaration2R1: {
		symbols.NT_AttributeDeclaration, 2, 1, 
		symbols.Symbols{  
			symbols.NT_AttributeName, 
			symbols.NT_TypeName, 
			symbols.T_5, 
			symbols.NT_Constraints,
		}, 
		AttributeDeclaration2R1, 
	},
	AttributeDeclaration2R2: {
		symbols.NT_AttributeDeclaration, 2, 2, 
		symbols.Symbols{  
			symbols.NT_AttributeName, 
			symbols.NT_TypeName, 
			symbols.T_5, 
			symbols.NT_Constraints,
		}, 
		AttributeDeclaration2R2, 
	},
	AttributeDeclaration2R3: {
		symbols.NT_AttributeDeclaration, 2, 3, 
		symbols.Symbols{  
			symbols.NT_AttributeName, 
			symbols.NT_TypeName, 
			symbols.T_5, 
			symbols.NT_Constraints,
		}, 
		AttributeDeclaration2R3, 
	},
	AttributeDeclaration2R4: {
		symbols.NT_AttributeDeclaration, 2, 4, 
		symbols.Symbols{  
			symbols.NT_AttributeName, 
			symbols.NT_TypeName, 
			symbols.T_5, 
			symbols.NT_Constraints,
		}, 
		AttributeDeclaration2R4, 
	},
	AttributeDeclarations0R0: {
		symbols.NT_AttributeDeclarations, 0, 0, 
		symbols.Symbols{  
			symbols.NT_AttributeDeclaration,
		}, 
		AttributeDeclarations0R0, 
	},
	AttributeDeclarations0R1: {
		symbols.NT_AttributeDeclarations, 0, 1, 
		symbols.Symbols{  
			symbols.NT_AttributeDeclaration,
		}, 
		AttributeDeclarations0R1, 
	},
	AttributeDeclarations1R0: {
		symbols.NT_AttributeDeclarations, 1, 0, 
		symbols.Symbols{  
			symbols.NT_AttributeDeclaration, 
			symbols.NT_AttributeDeclarations,
		}, 
		AttributeDeclarations1R0, 
	},
	AttributeDeclarations1R1: {
		symbols.NT_AttributeDeclarations, 1, 1, 
		symbols.Symbols{  
			symbols.NT_AttributeDeclaration, 
			symbols.NT_AttributeDeclarations,
		}, 
		AttributeDeclarations1R1, 
	},
	AttributeDeclarations1R2: {
		symbols.NT_AttributeDeclarations, 1, 2, 
		symbols.Symbols{  
			symbols.NT_AttributeDeclaration, 
			symbols.NT_AttributeDeclarations,
		}, 
		AttributeDeclarations1R2, 
	},
	AttributeName0R0: {
		symbols.NT_AttributeName, 0, 0, 
		symbols.Symbols{  
			symbols.NT_Name,
		}, 
		AttributeName0R0, 
	},
	AttributeName0R1: {
		symbols.NT_AttributeName, 0, 1, 
		symbols.Symbols{  
			symbols.NT_Name,
		}, 
		AttributeName0R1, 
	},
	Constraint0R0: {
		symbols.NT_Constraint, 0, 0, 
		symbols.Symbols{  
			symbols.NT_ForeignKey,
		}, 
		Constraint0R0, 
	},
	Constraint0R1: {
		symbols.NT_Constraint, 0, 1, 
		symbols.Symbols{  
			symbols.NT_ForeignKey,
		}, 
		Constraint0R1, 
	},
	Constraint1R0: {
		symbols.NT_Constraint, 1, 0, 
		symbols.Symbols{  
			symbols.NT_Nullable,
		}, 
		Constraint1R0, 
	},
	Constraint1R1: {
		symbols.NT_Constraint, 1, 1, 
		symbols.Symbols{  
			symbols.NT_Nullable,
		}, 
		Constraint1R1, 
	},
	Constraint2R0: {
		symbols.NT_Constraint, 2, 0, 
		symbols.Symbols{  
			symbols.NT_Unique,
		}, 
		Constraint2R0, 
	},
	Constraint2R1: {
		symbols.NT_Constraint, 2, 1, 
		symbols.Symbols{  
			symbols.NT_Unique,
		}, 
		Constraint2R1, 
	},
	Constraints0R0: {
		symbols.NT_Constraints, 0, 0, 
		symbols.Symbols{  
			symbols.NT_Constraint, 
			symbols.NT_Constraints,
		}, 
		Constraints0R0, 
	},
	Constraints0R1: {
		symbols.NT_Constraints, 0, 1, 
		symbols.Symbols{  
			symbols.NT_Constraint, 
			symbols.NT_Constraints,
		}, 
		Constraints0R1, 
	},
	Constraints0R2: {
		symbols.NT_Constraints, 0, 2, 
		symbols.Symbols{  
			symbols.NT_Constraint, 
			symbols.NT_Constraints,
		}, 
		Constraints0R2, 
	},
	Constraints1R0: {
		symbols.NT_Constraints, 1, 0, 
		symbols.Symbols{ 
		}, 
		Constraints1R0, 
	},
	Description0R0: {
		symbols.NT_Description, 0, 0, 
		symbols.Symbols{  
			symbols.T_19,
		}, 
		Description0R0, 
	},
	Description0R1: {
		symbols.NT_Description, 0, 1, 
		symbols.Symbols{  
			symbols.T_19,
		}, 
		Description0R1, 
	},
	Description1R0: {
		symbols.NT_Description, 1, 0, 
		symbols.Symbols{ 
		}, 
		Description1R0, 
	},
	ERM0R0: {
		symbols.NT_ERM, 0, 0, 
		symbols.Symbols{  
			symbols.NT_EntityOrEnum, 
			symbols.NT_ERM,
		}, 
		ERM0R0, 
	},
	ERM0R1: {
		symbols.NT_ERM, 0, 1, 
		symbols.Symbols{  
			symbols.NT_EntityOrEnum, 
			symbols.NT_ERM,
		}, 
		ERM0R1, 
	},
	ERM0R2: {
		symbols.NT_ERM, 0, 2, 
		symbols.Symbols{  
			symbols.NT_EntityOrEnum, 
			symbols.NT_ERM,
		}, 
		ERM0R2, 
	},
	ERM1R0: {
		symbols.NT_ERM, 1, 0, 
		symbols.Symbols{  
			symbols.NT_EntityOrEnum,
		}, 
		ERM1R0, 
	},
	ERM1R1: {
		symbols.NT_ERM, 1, 1, 
		symbols.Symbols{  
			symbols.NT_EntityOrEnum,
		}, 
		ERM1R1, 
	},
	Entity0R0: {
		symbols.NT_Entity, 0, 0, 
		symbols.Symbols{  
			symbols.NT_EntityName, 
			symbols.T_23, 
			symbols.NT_AttributeDeclarations, 
			symbols.T_24,
		}, 
		Entity0R0, 
	},
	Entity0R1: {
		symbols.NT_Entity, 0, 1, 
		symbols.Symbols{  
			symbols.NT_EntityName, 
			symbols.T_23, 
			symbols.NT_AttributeDeclarations, 
			symbols.T_24,
		}, 
		Entity0R1, 
	},
	Entity0R2: {
		symbols.NT_Entity, 0, 2, 
		symbols.Symbols{  
			symbols.NT_EntityName, 
			symbols.T_23, 
			symbols.NT_AttributeDeclarations, 
			symbols.T_24,
		}, 
		Entity0R2, 
	},
	Entity0R3: {
		symbols.NT_Entity, 0, 3, 
		symbols.Symbols{  
			symbols.NT_EntityName, 
			symbols.T_23, 
			symbols.NT_AttributeDeclarations, 
			symbols.T_24,
		}, 
		Entity0R3, 
	},
	Entity0R4: {
		symbols.NT_Entity, 0, 4, 
		symbols.Symbols{  
			symbols.NT_EntityName, 
			symbols.T_23, 
			symbols.NT_AttributeDeclarations, 
			symbols.T_24,
		}, 
		Entity0R4, 
	},
	Entity1R0: {
		symbols.NT_Entity, 1, 0, 
		symbols.Symbols{  
			symbols.NT_EntityName, 
			symbols.T_23, 
			symbols.T_24,
		}, 
		Entity1R0, 
	},
	Entity1R1: {
		symbols.NT_Entity, 1, 1, 
		symbols.Symbols{  
			symbols.NT_EntityName, 
			symbols.T_23, 
			symbols.T_24,
		}, 
		Entity1R1, 
	},
	Entity1R2: {
		symbols.NT_Entity, 1, 2, 
		symbols.Symbols{  
			symbols.NT_EntityName, 
			symbols.T_23, 
			symbols.T_24,
		}, 
		Entity1R2, 
	},
	Entity1R3: {
		symbols.NT_Entity, 1, 3, 
		symbols.Symbols{  
			symbols.NT_EntityName, 
			symbols.T_23, 
			symbols.T_24,
		}, 
		Entity1R3, 
	},
	EntityName0R0: {
		symbols.NT_EntityName, 0, 0, 
		symbols.Symbols{  
			symbols.NT_Name,
		}, 
		EntityName0R0, 
	},
	EntityName0R1: {
		symbols.NT_EntityName, 0, 1, 
		symbols.Symbols{  
			symbols.NT_Name,
		}, 
		EntityName0R1, 
	},
	EntityOrEnum0R0: {
		symbols.NT_EntityOrEnum, 0, 0, 
		symbols.Symbols{  
			symbols.NT_Entity,
		}, 
		EntityOrEnum0R0, 
	},
	EntityOrEnum0R1: {
		symbols.NT_EntityOrEnum, 0, 1, 
		symbols.Symbols{  
			symbols.NT_Entity,
		}, 
		EntityOrEnum0R1, 
	},
	EntityOrEnum1R0: {
		symbols.NT_EntityOrEnum, 1, 0, 
		symbols.Symbols{  
			symbols.NT_Enum,
		}, 
		EntityOrEnum1R0, 
	},
	EntityOrEnum1R1: {
		symbols.NT_EntityOrEnum, 1, 1, 
		symbols.Symbols{  
			symbols.NT_Enum,
		}, 
		EntityOrEnum1R1, 
	},
	Enum0R0: {
		symbols.NT_Enum, 0, 0, 
		symbols.Symbols{  
			symbols.T_10, 
			symbols.T_13, 
			symbols.T_23, 
			symbols.NT_EnumItems, 
			symbols.T_24,
		}, 
		Enum0R0, 
	},
	Enum0R1: {
		symbols.NT_Enum, 0, 1, 
		symbols.Symbols{  
			symbols.T_10, 
			symbols.T_13, 
			symbols.T_23, 
			symbols.NT_EnumItems, 
			symbols.T_24,
		}, 
		Enum0R1, 
	},
	Enum0R2: {
		symbols.NT_Enum, 0, 2, 
		symbols.Symbols{  
			symbols.T_10, 
			symbols.T_13, 
			symbols.T_23, 
			symbols.NT_EnumItems, 
			symbols.T_24,
		}, 
		Enum0R2, 
	},
	Enum0R3: {
		symbols.NT_Enum, 0, 3, 
		symbols.Symbols{  
			symbols.T_10, 
			symbols.T_13, 
			symbols.T_23, 
			symbols.NT_EnumItems, 
			symbols.T_24,
		}, 
		Enum0R3, 
	},
	Enum0R4: {
		symbols.NT_Enum, 0, 4, 
		symbols.Symbols{  
			symbols.T_10, 
			symbols.T_13, 
			symbols.T_23, 
			symbols.NT_EnumItems, 
			symbols.T_24,
		}, 
		Enum0R4, 
	},
	Enum0R5: {
		symbols.NT_Enum, 0, 5, 
		symbols.Symbols{  
			symbols.T_10, 
			symbols.T_13, 
			symbols.T_23, 
			symbols.NT_EnumItems, 
			symbols.T_24,
		}, 
		Enum0R5, 
	},
	EnumItem0R0: {
		symbols.NT_EnumItem, 0, 0, 
		symbols.Symbols{  
			symbols.NT_EnumItemName, 
			symbols.NT_Description, 
			symbols.T_2, 
			symbols.NT_SequenceNumber, 
			symbols.T_1,
		}, 
		EnumItem0R0, 
	},
	EnumItem0R1: {
		symbols.NT_EnumItem, 0, 1, 
		symbols.Symbols{  
			symbols.NT_EnumItemName, 
			symbols.NT_Description, 
			symbols.T_2, 
			symbols.NT_SequenceNumber, 
			symbols.T_1,
		}, 
		EnumItem0R1, 
	},
	EnumItem0R2: {
		symbols.NT_EnumItem, 0, 2, 
		symbols.Symbols{  
			symbols.NT_EnumItemName, 
			symbols.NT_Description, 
			symbols.T_2, 
			symbols.NT_SequenceNumber, 
			symbols.T_1,
		}, 
		EnumItem0R2, 
	},
	EnumItem0R3: {
		symbols.NT_EnumItem, 0, 3, 
		symbols.Symbols{  
			symbols.NT_EnumItemName, 
			symbols.NT_Description, 
			symbols.T_2, 
			symbols.NT_SequenceNumber, 
			symbols.T_1,
		}, 
		EnumItem0R3, 
	},
	EnumItem0R4: {
		symbols.NT_EnumItem, 0, 4, 
		symbols.Symbols{  
			symbols.NT_EnumItemName, 
			symbols.NT_Description, 
			symbols.T_2, 
			symbols.NT_SequenceNumber, 
			symbols.T_1,
		}, 
		EnumItem0R4, 
	},
	EnumItem0R5: {
		symbols.NT_EnumItem, 0, 5, 
		symbols.Symbols{  
			symbols.NT_EnumItemName, 
			symbols.NT_Description, 
			symbols.T_2, 
			symbols.NT_SequenceNumber, 
			symbols.T_1,
		}, 
		EnumItem0R5, 
	},
	EnumItemName0R0: {
		symbols.NT_EnumItemName, 0, 0, 
		symbols.Symbols{  
			symbols.T_19,
		}, 
		EnumItemName0R0, 
	},
	EnumItemName0R1: {
		symbols.NT_EnumItemName, 0, 1, 
		symbols.Symbols{  
			symbols.T_19,
		}, 
		EnumItemName0R1, 
	},
	EnumItems0R0: {
		symbols.NT_EnumItems, 0, 0, 
		symbols.Symbols{  
			symbols.NT_EnumItem, 
			symbols.NT_EnumItems,
		}, 
		EnumItems0R0, 
	},
	EnumItems0R1: {
		symbols.NT_EnumItems, 0, 1, 
		symbols.Symbols{  
			symbols.NT_EnumItem, 
			symbols.NT_EnumItems,
		}, 
		EnumItems0R1, 
	},
	EnumItems0R2: {
		symbols.NT_EnumItems, 0, 2, 
		symbols.Symbols{  
			symbols.NT_EnumItem, 
			symbols.NT_EnumItems,
		}, 
		EnumItems0R2, 
	},
	EnumItems1R0: {
		symbols.NT_EnumItems, 1, 0, 
		symbols.Symbols{  
			symbols.NT_EnumItem,
		}, 
		EnumItems1R0, 
	},
	EnumItems1R1: {
		symbols.NT_EnumItems, 1, 1, 
		symbols.Symbols{  
			symbols.NT_EnumItem,
		}, 
		EnumItems1R1, 
	},
	FieldName0R0: {
		symbols.NT_FieldName, 0, 0, 
		symbols.Symbols{  
			symbols.NT_Name,
		}, 
		FieldName0R0, 
	},
	FieldName0R1: {
		symbols.NT_FieldName, 0, 1, 
		symbols.Symbols{  
			symbols.NT_Name,
		}, 
		FieldName0R1, 
	},
	ForeignKey0R0: {
		symbols.NT_ForeignKey, 0, 0, 
		symbols.Symbols{  
			symbols.T_3, 
			symbols.NT_EntityName, 
			symbols.T_0, 
			symbols.NT_FieldName,
		}, 
		ForeignKey0R0, 
	},
	ForeignKey0R1: {
		symbols.NT_ForeignKey, 0, 1, 
		symbols.Symbols{  
			symbols.T_3, 
			symbols.NT_EntityName, 
			symbols.T_0, 
			symbols.NT_FieldName,
		}, 
		ForeignKey0R1, 
	},
	ForeignKey0R2: {
		symbols.NT_ForeignKey, 0, 2, 
		symbols.Symbols{  
			symbols.T_3, 
			symbols.NT_EntityName, 
			symbols.T_0, 
			symbols.NT_FieldName,
		}, 
		ForeignKey0R2, 
	},
	ForeignKey0R3: {
		symbols.NT_ForeignKey, 0, 3, 
		symbols.Symbols{  
			symbols.T_3, 
			symbols.NT_EntityName, 
			symbols.T_0, 
			symbols.NT_FieldName,
		}, 
		ForeignKey0R3, 
	},
	ForeignKey0R4: {
		symbols.NT_ForeignKey, 0, 4, 
		symbols.Symbols{  
			symbols.T_3, 
			symbols.NT_EntityName, 
			symbols.T_0, 
			symbols.NT_FieldName,
		}, 
		ForeignKey0R4, 
	},
	Name0R0: {
		symbols.NT_Name, 0, 0, 
		symbols.Symbols{  
			symbols.T_13,
		}, 
		Name0R0, 
	},
	Name0R1: {
		symbols.NT_Name, 0, 1, 
		symbols.Symbols{  
			symbols.T_13,
		}, 
		Name0R1, 
	},
	Nullable0R0: {
		symbols.NT_Nullable, 0, 0, 
		symbols.Symbols{  
			symbols.T_15,
		}, 
		Nullable0R0, 
	},
	Nullable0R1: {
		symbols.NT_Nullable, 0, 1, 
		symbols.Symbols{  
			symbols.T_15,
		}, 
		Nullable0R1, 
	},
	Nullable1R0: {
		symbols.NT_Nullable, 1, 0, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_15,
		}, 
		Nullable1R0, 
	},
	Nullable1R1: {
		symbols.NT_Nullable, 1, 1, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_15,
		}, 
		Nullable1R1, 
	},
	Nullable1R2: {
		symbols.NT_Nullable, 1, 2, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_15,
		}, 
		Nullable1R2, 
	},
	PrimaryKey0R0: {
		symbols.NT_PrimaryKey, 0, 0, 
		symbols.Symbols{  
			symbols.T_4,
		}, 
		PrimaryKey0R0, 
	},
	PrimaryKey0R1: {
		symbols.NT_PrimaryKey, 0, 1, 
		symbols.Symbols{  
			symbols.T_4,
		}, 
		PrimaryKey0R1, 
	},
	Schema0R0: {
		symbols.NT_Schema, 0, 0, 
		symbols.Symbols{  
			symbols.T_17, 
			symbols.NT_SchemaName, 
			symbols.NT_ERM,
		}, 
		Schema0R0, 
	},
	Schema0R1: {
		symbols.NT_Schema, 0, 1, 
		symbols.Symbols{  
			symbols.T_17, 
			symbols.NT_SchemaName, 
			symbols.NT_ERM,
		}, 
		Schema0R1, 
	},
	Schema0R2: {
		symbols.NT_Schema, 0, 2, 
		symbols.Symbols{  
			symbols.T_17, 
			symbols.NT_SchemaName, 
			symbols.NT_ERM,
		}, 
		Schema0R2, 
	},
	Schema0R3: {
		symbols.NT_Schema, 0, 3, 
		symbols.Symbols{  
			symbols.T_17, 
			symbols.NT_SchemaName, 
			symbols.NT_ERM,
		}, 
		Schema0R3, 
	},
	SchemaName0R0: {
		symbols.NT_SchemaName, 0, 0, 
		symbols.Symbols{  
			symbols.NT_Name,
		}, 
		SchemaName0R0, 
	},
	SchemaName0R1: {
		symbols.NT_SchemaName, 0, 1, 
		symbols.Symbols{  
			symbols.NT_Name,
		}, 
		SchemaName0R1, 
	},
	SequenceNumber0R0: {
		symbols.NT_SequenceNumber, 0, 0, 
		symbols.Symbols{  
			symbols.T_16,
		}, 
		SequenceNumber0R0, 
	},
	SequenceNumber0R1: {
		symbols.NT_SequenceNumber, 0, 1, 
		symbols.Symbols{  
			symbols.T_16,
		}, 
		SequenceNumber0R1, 
	},
	TypeName0R0: {
		symbols.NT_TypeName, 0, 0, 
		symbols.Symbols{  
			symbols.T_6,
		}, 
		TypeName0R0, 
	},
	TypeName0R1: {
		symbols.NT_TypeName, 0, 1, 
		symbols.Symbols{  
			symbols.T_6,
		}, 
		TypeName0R1, 
	},
	TypeName1R0: {
		symbols.NT_TypeName, 1, 0, 
		symbols.Symbols{  
			symbols.T_7,
		}, 
		TypeName1R0, 
	},
	TypeName1R1: {
		symbols.NT_TypeName, 1, 1, 
		symbols.Symbols{  
			symbols.T_7,
		}, 
		TypeName1R1, 
	},
	TypeName2R0: {
		symbols.NT_TypeName, 2, 0, 
		symbols.Symbols{  
			symbols.T_8,
		}, 
		TypeName2R0, 
	},
	TypeName2R1: {
		symbols.NT_TypeName, 2, 1, 
		symbols.Symbols{  
			symbols.T_8,
		}, 
		TypeName2R1, 
	},
	TypeName3R0: {
		symbols.NT_TypeName, 3, 0, 
		symbols.Symbols{  
			symbols.T_9,
		}, 
		TypeName3R0, 
	},
	TypeName3R1: {
		symbols.NT_TypeName, 3, 1, 
		symbols.Symbols{  
			symbols.T_9,
		}, 
		TypeName3R1, 
	},
	TypeName4R0: {
		symbols.NT_TypeName, 4, 0, 
		symbols.Symbols{  
			symbols.T_11,
		}, 
		TypeName4R0, 
	},
	TypeName4R1: {
		symbols.NT_TypeName, 4, 1, 
		symbols.Symbols{  
			symbols.T_11,
		}, 
		TypeName4R1, 
	},
	TypeName5R0: {
		symbols.NT_TypeName, 5, 0, 
		symbols.Symbols{  
			symbols.T_18,
		}, 
		TypeName5R0, 
	},
	TypeName5R1: {
		symbols.NT_TypeName, 5, 1, 
		symbols.Symbols{  
			symbols.T_18,
		}, 
		TypeName5R1, 
	},
	TypeName6R0: {
		symbols.NT_TypeName, 6, 0, 
		symbols.Symbols{  
			symbols.T_20,
		}, 
		TypeName6R0, 
	},
	TypeName6R1: {
		symbols.NT_TypeName, 6, 1, 
		symbols.Symbols{  
			symbols.T_20,
		}, 
		TypeName6R1, 
	},
	TypeName7R0: {
		symbols.NT_TypeName, 7, 0, 
		symbols.Symbols{  
			symbols.T_21,
		}, 
		TypeName7R0, 
	},
	TypeName7R1: {
		symbols.NT_TypeName, 7, 1, 
		symbols.Symbols{  
			symbols.T_21,
		}, 
		TypeName7R1, 
	},
	Unique0R0: {
		symbols.NT_Unique, 0, 0, 
		symbols.Symbols{  
			symbols.T_22,
		}, 
		Unique0R0, 
	},
	Unique0R1: {
		symbols.NT_Unique, 0, 1, 
		symbols.Symbols{  
			symbols.T_22,
		}, 
		Unique0R1, 
	},
}

var slotIndex = map[Index]Label { 
	Index{ symbols.NT_AttributeDeclaration,0,0 }: AttributeDeclaration0R0,
	Index{ symbols.NT_AttributeDeclaration,0,1 }: AttributeDeclaration0R1,
	Index{ symbols.NT_AttributeDeclaration,0,2 }: AttributeDeclaration0R2,
	Index{ symbols.NT_AttributeDeclaration,0,3 }: AttributeDeclaration0R3,
	Index{ symbols.NT_AttributeDeclaration,1,0 }: AttributeDeclaration1R0,
	Index{ symbols.NT_AttributeDeclaration,1,1 }: AttributeDeclaration1R1,
	Index{ symbols.NT_AttributeDeclaration,1,2 }: AttributeDeclaration1R2,
	Index{ symbols.NT_AttributeDeclaration,1,3 }: AttributeDeclaration1R3,
	Index{ symbols.NT_AttributeDeclaration,2,0 }: AttributeDeclaration2R0,
	Index{ symbols.NT_AttributeDeclaration,2,1 }: AttributeDeclaration2R1,
	Index{ symbols.NT_AttributeDeclaration,2,2 }: AttributeDeclaration2R2,
	Index{ symbols.NT_AttributeDeclaration,2,3 }: AttributeDeclaration2R3,
	Index{ symbols.NT_AttributeDeclaration,2,4 }: AttributeDeclaration2R4,
	Index{ symbols.NT_AttributeDeclarations,0,0 }: AttributeDeclarations0R0,
	Index{ symbols.NT_AttributeDeclarations,0,1 }: AttributeDeclarations0R1,
	Index{ symbols.NT_AttributeDeclarations,1,0 }: AttributeDeclarations1R0,
	Index{ symbols.NT_AttributeDeclarations,1,1 }: AttributeDeclarations1R1,
	Index{ symbols.NT_AttributeDeclarations,1,2 }: AttributeDeclarations1R2,
	Index{ symbols.NT_AttributeName,0,0 }: AttributeName0R0,
	Index{ symbols.NT_AttributeName,0,1 }: AttributeName0R1,
	Index{ symbols.NT_Constraint,0,0 }: Constraint0R0,
	Index{ symbols.NT_Constraint,0,1 }: Constraint0R1,
	Index{ symbols.NT_Constraint,1,0 }: Constraint1R0,
	Index{ symbols.NT_Constraint,1,1 }: Constraint1R1,
	Index{ symbols.NT_Constraint,2,0 }: Constraint2R0,
	Index{ symbols.NT_Constraint,2,1 }: Constraint2R1,
	Index{ symbols.NT_Constraints,0,0 }: Constraints0R0,
	Index{ symbols.NT_Constraints,0,1 }: Constraints0R1,
	Index{ symbols.NT_Constraints,0,2 }: Constraints0R2,
	Index{ symbols.NT_Constraints,1,0 }: Constraints1R0,
	Index{ symbols.NT_Description,0,0 }: Description0R0,
	Index{ symbols.NT_Description,0,1 }: Description0R1,
	Index{ symbols.NT_Description,1,0 }: Description1R0,
	Index{ symbols.NT_ERM,0,0 }: ERM0R0,
	Index{ symbols.NT_ERM,0,1 }: ERM0R1,
	Index{ symbols.NT_ERM,0,2 }: ERM0R2,
	Index{ symbols.NT_ERM,1,0 }: ERM1R0,
	Index{ symbols.NT_ERM,1,1 }: ERM1R1,
	Index{ symbols.NT_Entity,0,0 }: Entity0R0,
	Index{ symbols.NT_Entity,0,1 }: Entity0R1,
	Index{ symbols.NT_Entity,0,2 }: Entity0R2,
	Index{ symbols.NT_Entity,0,3 }: Entity0R3,
	Index{ symbols.NT_Entity,0,4 }: Entity0R4,
	Index{ symbols.NT_Entity,1,0 }: Entity1R0,
	Index{ symbols.NT_Entity,1,1 }: Entity1R1,
	Index{ symbols.NT_Entity,1,2 }: Entity1R2,
	Index{ symbols.NT_Entity,1,3 }: Entity1R3,
	Index{ symbols.NT_EntityName,0,0 }: EntityName0R0,
	Index{ symbols.NT_EntityName,0,1 }: EntityName0R1,
	Index{ symbols.NT_EntityOrEnum,0,0 }: EntityOrEnum0R0,
	Index{ symbols.NT_EntityOrEnum,0,1 }: EntityOrEnum0R1,
	Index{ symbols.NT_EntityOrEnum,1,0 }: EntityOrEnum1R0,
	Index{ symbols.NT_EntityOrEnum,1,1 }: EntityOrEnum1R1,
	Index{ symbols.NT_Enum,0,0 }: Enum0R0,
	Index{ symbols.NT_Enum,0,1 }: Enum0R1,
	Index{ symbols.NT_Enum,0,2 }: Enum0R2,
	Index{ symbols.NT_Enum,0,3 }: Enum0R3,
	Index{ symbols.NT_Enum,0,4 }: Enum0R4,
	Index{ symbols.NT_Enum,0,5 }: Enum0R5,
	Index{ symbols.NT_EnumItem,0,0 }: EnumItem0R0,
	Index{ symbols.NT_EnumItem,0,1 }: EnumItem0R1,
	Index{ symbols.NT_EnumItem,0,2 }: EnumItem0R2,
	Index{ symbols.NT_EnumItem,0,3 }: EnumItem0R3,
	Index{ symbols.NT_EnumItem,0,4 }: EnumItem0R4,
	Index{ symbols.NT_EnumItem,0,5 }: EnumItem0R5,
	Index{ symbols.NT_EnumItemName,0,0 }: EnumItemName0R0,
	Index{ symbols.NT_EnumItemName,0,1 }: EnumItemName0R1,
	Index{ symbols.NT_EnumItems,0,0 }: EnumItems0R0,
	Index{ symbols.NT_EnumItems,0,1 }: EnumItems0R1,
	Index{ symbols.NT_EnumItems,0,2 }: EnumItems0R2,
	Index{ symbols.NT_EnumItems,1,0 }: EnumItems1R0,
	Index{ symbols.NT_EnumItems,1,1 }: EnumItems1R1,
	Index{ symbols.NT_FieldName,0,0 }: FieldName0R0,
	Index{ symbols.NT_FieldName,0,1 }: FieldName0R1,
	Index{ symbols.NT_ForeignKey,0,0 }: ForeignKey0R0,
	Index{ symbols.NT_ForeignKey,0,1 }: ForeignKey0R1,
	Index{ symbols.NT_ForeignKey,0,2 }: ForeignKey0R2,
	Index{ symbols.NT_ForeignKey,0,3 }: ForeignKey0R3,
	Index{ symbols.NT_ForeignKey,0,4 }: ForeignKey0R4,
	Index{ symbols.NT_Name,0,0 }: Name0R0,
	Index{ symbols.NT_Name,0,1 }: Name0R1,
	Index{ symbols.NT_Nullable,0,0 }: Nullable0R0,
	Index{ symbols.NT_Nullable,0,1 }: Nullable0R1,
	Index{ symbols.NT_Nullable,1,0 }: Nullable1R0,
	Index{ symbols.NT_Nullable,1,1 }: Nullable1R1,
	Index{ symbols.NT_Nullable,1,2 }: Nullable1R2,
	Index{ symbols.NT_PrimaryKey,0,0 }: PrimaryKey0R0,
	Index{ symbols.NT_PrimaryKey,0,1 }: PrimaryKey0R1,
	Index{ symbols.NT_Schema,0,0 }: Schema0R0,
	Index{ symbols.NT_Schema,0,1 }: Schema0R1,
	Index{ symbols.NT_Schema,0,2 }: Schema0R2,
	Index{ symbols.NT_Schema,0,3 }: Schema0R3,
	Index{ symbols.NT_SchemaName,0,0 }: SchemaName0R0,
	Index{ symbols.NT_SchemaName,0,1 }: SchemaName0R1,
	Index{ symbols.NT_SequenceNumber,0,0 }: SequenceNumber0R0,
	Index{ symbols.NT_SequenceNumber,0,1 }: SequenceNumber0R1,
	Index{ symbols.NT_TypeName,0,0 }: TypeName0R0,
	Index{ symbols.NT_TypeName,0,1 }: TypeName0R1,
	Index{ symbols.NT_TypeName,1,0 }: TypeName1R0,
	Index{ symbols.NT_TypeName,1,1 }: TypeName1R1,
	Index{ symbols.NT_TypeName,2,0 }: TypeName2R0,
	Index{ symbols.NT_TypeName,2,1 }: TypeName2R1,
	Index{ symbols.NT_TypeName,3,0 }: TypeName3R0,
	Index{ symbols.NT_TypeName,3,1 }: TypeName3R1,
	Index{ symbols.NT_TypeName,4,0 }: TypeName4R0,
	Index{ symbols.NT_TypeName,4,1 }: TypeName4R1,
	Index{ symbols.NT_TypeName,5,0 }: TypeName5R0,
	Index{ symbols.NT_TypeName,5,1 }: TypeName5R1,
	Index{ symbols.NT_TypeName,6,0 }: TypeName6R0,
	Index{ symbols.NT_TypeName,6,1 }: TypeName6R1,
	Index{ symbols.NT_TypeName,7,0 }: TypeName7R0,
	Index{ symbols.NT_TypeName,7,1 }: TypeName7R1,
	Index{ symbols.NT_Unique,0,0 }: Unique0R0,
	Index{ symbols.NT_Unique,0,1 }: Unique0R1,
}

var alternates = map[symbols.NT][]Label{ 
	symbols.NT_Schema:[]Label{ Schema0R0 },
	symbols.NT_AttributeDeclaration:[]Label{ AttributeDeclaration0R0,AttributeDeclaration1R0,AttributeDeclaration2R0 },
	symbols.NT_AttributeDeclarations:[]Label{ AttributeDeclarations0R0,AttributeDeclarations1R0 },
	symbols.NT_AttributeName:[]Label{ AttributeName0R0 },
	symbols.NT_Constraint:[]Label{ Constraint0R0,Constraint1R0,Constraint2R0 },
	symbols.NT_Constraints:[]Label{ Constraints0R0,Constraints1R0 },
	symbols.NT_Description:[]Label{ Description0R0,Description1R0 },
	symbols.NT_Entity:[]Label{ Entity0R0,Entity1R0 },
	symbols.NT_EntityName:[]Label{ EntityName0R0 },
	symbols.NT_EntityOrEnum:[]Label{ EntityOrEnum0R0,EntityOrEnum1R0 },
	symbols.NT_Enum:[]Label{ Enum0R0 },
	symbols.NT_EnumItem:[]Label{ EnumItem0R0 },
	symbols.NT_EnumItemName:[]Label{ EnumItemName0R0 },
	symbols.NT_EnumItems:[]Label{ EnumItems0R0,EnumItems1R0 },
	symbols.NT_ERM:[]Label{ ERM0R0,ERM1R0 },
	symbols.NT_FieldName:[]Label{ FieldName0R0 },
	symbols.NT_ForeignKey:[]Label{ ForeignKey0R0 },
	symbols.NT_Name:[]Label{ Name0R0 },
	symbols.NT_Nullable:[]Label{ Nullable0R0,Nullable1R0 },
	symbols.NT_PrimaryKey:[]Label{ PrimaryKey0R0 },
	symbols.NT_SchemaName:[]Label{ SchemaName0R0 },
	symbols.NT_SequenceNumber:[]Label{ SequenceNumber0R0 },
	symbols.NT_TypeName:[]Label{ TypeName0R0,TypeName1R0,TypeName2R0,TypeName3R0,TypeName4R0,TypeName5R0,TypeName6R0,TypeName7R0 },
	symbols.NT_Unique:[]Label{ Unique0R0 },
}

